### ISSUE TITLE
synchronized structures are not available in gwt

### ISSUE THREAD

**Issue by hellerst** [mini2Dx/mini2Dx#12]
If the target platform is HTML5 this is realized via gwt in libgdx. gwt does not support synchronized structures (ConcurrentHashMap etc) and it is required to modify your API source code for this platform. As far as I know the synchronized structures are not required as libgdx and gwt run single threaded.

**Comment by tomcashman** [comment]
Closing this issue as HTML5 support was dropped a good while ago and the API implementation has changed a lot since this issue was logged.

If HTML5 support is to be added in the future, a new roadmap and set of issues will be created based on the API implementation at the time.
