### ISSUE TITLE
Create sample/tutorial games

### ISSUE THREAD

**Issue by tomcashman** [mini2Dx/mini2Dx#19]
We need sample and/or tutorial games so people can learn to use the framework by example. The samples repository can be found here for any pull requests -> https://github.com/tomcashman/mini2Dx-samples

**Comment by tomcashman** [comment]
Currently in progress at the following repositories:
https://github.com/mini2Dx/mini2Dx-sample-tictactoe
https://github.com/mini2Dx/mini2Dx-sample-invaders

**Comment by tomcashman** [comment]
New samples available at:
 * https://github.com/mini2Dx/mini2Dx-sample-breakout
 * https://github.com/mini2Dx/mini2Dx-sample-tappy-bird
 * https://github.com/mini2Dx/mini2Dx-sample-connect4

**Comment by kevin4dhd** [comment]
example with box2d please?

**Comment by tomcashman** [comment]
Currently LibGDX's box2D extension wouldn't be 100% supported in 2.0 since it won't work on games consoles. If you're planning on using it you'd be limited to just mobile + PC. We'll need to work on a solution for that once 2.0 is finished.

**Comment by kevin4dhd** [comment]
I really like version 2.0, but I am having a hard time making a platform game, I would like to know if there is an easy way to do it with version 2.0 or should it be done the old way with math and vector2?
