### ISSUE TITLE
Old Android project template

### ISSUE THREAD

**Issue by MauroCoppola** [mini2Dx/mini2Dx#193]
I tried to generate a new project using generator [linked in the wiki](https://github.com/mini2Dx/mini2Dx/wiki/Setting-up-your-project) and it seems that Android template is old (for example minSdkVersion is still specified in Manifest and default minSdkVersion is too low for most recent Gradle plugin). Is there a more recent version of project generator or did I anything wrong?

**Comment by augustozanellato** [comment]
We've fixed this in mini2Dx/mini2Dx-project-generator master, @tomcashman just needs to tag a new release

**Comment by tomcashman** [comment]
I'll tag a new release this evening

**Comment by MauroCoppola** [comment]
Great! I'll close the issue as soon as the tag is updated. Thanks :)

**Comment by tomcashman** [comment]
Project generator has been updated :) -> https://github.com/mini2Dx/mini2Dx-project-generator/releases/tag/v1.2.3
