### ISSUE TITLE
Inaccurate Documentation?

### ISSUE THREAD

**Issue by drguildo** [mini2Dx/mini2Dx#22]
The tutorial says to export "gdx.jar, gdx-freetype.jar, mini2Dx-core.jar, mini2Dx-dependency-injection.jar, mini2Dx-ecs.jar and mini2Dx-tiled.jar", but they aren't listed in the Order and Export tab, I assume because they weren't added to the class path during that part of the tutorial.

**Comment by tomcashman** [comment]
Closing this issue as mini2Dx now provides a project generator tool and new wiki pages for setting up in IntelliJ and Eclipse.
