### ISSUE TITLE
Support LWJGL 3 Backend

### ISSUE THREAD

**Issue by Renaitare** [mini2Dx/mini2Dx#238]
By any chance, is there going to be added support for the LibGDX LWJGL 3 Backend anytime soon?

**Comment by tomcashman** [comment]
The current plan is to use LWJGL3 directly in the future. Though it may be possible that the LibGDX backend can be supported too. Is there a specific reason you need LWJGL3?

**Comment by Torbuntu** [comment]
Native arm32 and aarch64 builds.
Drag and drop files from OS to the running games.
Potentially better support for newer JDK.

These are a few top reasons I'd like it.

**Comment by tale** [comment]
> Native arm32 and aarch64 builds.
> Drag and drop files from OS to the running games.
> Potentially better support for newer JDK.
> 
> These are a few top reasons I'd like it.

Yeah it's mostly that especially the JDK

**Comment by tomcashman** [comment]
Currently available in 2.0 alpha
