### ISSUE TITLE
Can't run project generator for Mac

### ISSUE THREAD

**Issue by wilkon** [mini2Dx/mini2Dx#244]
Hey guys - new to this API. I couldn't find anything relating to this on your issues, so i thought i'd raise one. My apologies if it's already been addressed. 

I'm getting an error when opening the generator:
"“mini2Dx Project Generator” can’t be opened because Apple cannot check it for malicious software."
I'm not certain of the fix, but I did do a little digging and it seems that Catalina requires apps to be "notorized" (whatever [this](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution
) means). 

I also looked through the mini2dx generator github and found an older version (just one before release) that has the same issue.

Thanks a bunch for all your work, Mini2Dx Team.

**Comment by tomcashman** [comment]
I'll need to look into how to notarize Java applications. However, you might be able to work around this by holding down either CTRL or ALT, right-clicking the app and selecting Open.

**Comment by wilkon** [comment]
I've been able to figure out a workaround by disabling spctl via terminal
`sudo spctl --master-disable`
once this was disabled, the project generaotr ran with a security notice. once allowed, I could re-enable the spctl and it executed without any issues after this.
`sudo spctl --master-enable` to enable

Pretty sure this is what's causing it for most others if they do have the issue. Thanks for getting back so promptly - very much appreciated. You can decide if this closes the ticket or not :)

**Comment by augustozanellato** [comment]
FYI, when you have to open a non notarised app you just need to open it once, then you open System Preferences and go to `Security & Privacy - General` and then click on "Open anyways". It's a little bit annoying but it's still better than disabling GateKeeper altogether.
