### ISSUE TITLE
Mini2Dx 2 Alpha lwjgl3 back end Input issues

### ISSUE THREAD

**Issue by Torbuntu** [mini2Dx/mini2Dx#272]
Issue:
in Mini2Dx 2 alpha 25 and newer there is keyboard input lag.

Test:
Created a new project, updated to Mini2Dx 2 alpha 25, add Mdx.input.isKeyPressed(somekey) to move the generated template mini2Dx texture. Notice the input often does not respond.
The problem seems to get progressively more noticeable from alpha 25 and up. 

|System tested on||
|----|----|
|OS|Fedora Linux|
|Mini2Dx Version|2.0.0 alpha 25+| 
|Desktop Backend| Lwjgl3 |
|LibGDX Version| 1.9.10|

**Comment by Torbuntu** [comment]
When setting my Lwjgl3Mini2DxConfig target fps as so: `config.targetFPS = 60;` it seems to fix the lagging input, and I regain mostly normal controls. 

However, I now am seeing that `Mdx.input.isKeyJustPressed(int key)` sometimes fires multiple times.

**Comment by Torbuntu** [comment]
Just tried out doing a quick upgrade on [Sample Tappy Bird](https://github.com/mini2Dx/mini2Dx-sample-tappy-bird) bumping it to use alpha 28 with the lwjgl3 back end, and it also fires duplicate times on the `Mdx.input.isKeyJustPressed(int key)` method.

I modified the InputHandler as such:
```Java

public class InputHandler {

    int count = 0;

    boolean spacePressed() {
        if (Mdx.input.isKeyUp(Keys.SPACE)) {
            count = 0;
        }
        if (Mdx.input.isKeyJustPressed(Keys.SPACE)) {
            count++;

            System.out.println("Pressed: " + count);
            return true;
        } else {
            return false;
        }
    }
}
```

![image](https://user-images.githubusercontent.com/17347324/89473229-fc136200-d747-11ea-8c82-befd0609509a.png)

I'd imagine only ever seeing `Pressed: 1`right?

This happens in the lwjgl3 back end specifically.

**Comment by Torbuntu** [comment]
So with the fps fix this does not make sense to keep open. As for the other duplication issue that was due to me making waaaaay too many drawing calls. So not a real issue.

**Comment by tomcashman** [comment]
I've push a commit that should fix the issue. Can you clone the repo and run
```
./gradlew build publishToMavenLocal
```

And test 2.0.0-SNAPSHOT at 30 FPS on your build?
