### ISSUE TITLE
LibGdxGraphics.rotate() ignores x, y when degrees is zero

### ISSUE THREAD

**Issue by Feuermurmel** [mini2Dx/mini2Dx#279]
If `rotate()` has been called previously, `rotate(0, x, y)` should update the rotation center while keeping the rotation angle. The implementation of [LibGdxGraphics.rotate()](
https://github.com/mini2Dx/mini2Dx/blob/master/libgdx/src/main/java/org/mini2Dx/libgdx/LibgdxGraphics.java#L763) ignores the values of `x` and `y` when `degrees` is zero. I think this is a bug.

**Comment by tomcashman** [comment]
Fix available in `2.0.0-alpha.48`
