### ISSUE TITLE
Integrate artemis-odb library instead of your ecs?

### ISSUE THREAD

**Issue by rsredsq** [mini2Dx/mini2Dx#28]
Hey man!
Throw your look on the [artemis-odb library] (https://github.com/junkdog/artemis-odb).
Maybe it will be better to integrate this library, instead of your ecs?

**Comment by tomcashman** [comment]
mini2Dx's ECS library was removed pre-1.0.0. However, I want to leave this issue open as I would like to provide integration with artemis-ecs and/or ashley in future releases.
