### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by reymalahay** [mini2Dx/mini2Dx#308]
Hi all,

Is there a plan to add support for `kotlin`? After all, `kotlin` has become the _de facto_ language for developing Android [applications](https://kotlinlang.org/docs/android-overview.html) (and games)

Please advise.

Thanks in advance and kind regards,
rey malahay

**Comment by tomcashman** [comment]
Yep planning to add Kotlin support in 2.1

**Comment by reymalahay** [comment]
@tomcashman awesome, thanks.
