### ISSUE TITLE
Tiled Collisions Example - Failure to import TiledObject, TiledCollisionFactory, etc. after update

### ISSUE THREAD

**Issue by jfamulare** [mini2Dx/mini2Dx#32]
I tried to update my mini2dx project to the latest version, in eclipse, by doing Gradle refresh all after changing the version field in the build.gradle file to 1.1.0. I then looked in my Gradle Dependencies library under core and saw mini2dx-core-1.1.0.jar has been installed, but it doesn't have the Tiled package: "org.mini2dx.tiled". Am I doing something wrong in the update process or is something wrong on your end?

Thanks,
James

**Comment by tomcashman** [comment]
Is mini2Dx-tiled in your Gradle dependencies and set to 1.1.0?

**Comment by jfamulare** [comment]
Ok will do - thanks!

**Comment by tomcashman** [comment]
mini2Dx-tiled is now selectable (selected by default) in the mini2Dx Project Generator.
