### ISSUE TITLE
Gdx.input.isKeyJustPressed runs twice one each click

### ISSUE THREAD

**Issue by Khazrak** [mini2Dx/mini2Dx#34]
The Gdx.input.isKeyJustPressed is used so it doesn't evaluate true for holding down a key. This works fine in libgdx 1.6.4. On Mini2DX 1.1.0 this doesn't work.

The problem is that it runs twice. This is from the log that prints out every frame (from update-method):
1
1
1
1
1
1
1
1
DOWN
2
DOWN
3
3
3
3
3
3

I'm using ScreenBasedGame. 
Here is the code to reproduce the error: (put in update-method). 

if(Gdx.input.isKeyJustPressed(Input.Keys.UP))
        {
            System.out.println("UP");
            currentChoice = currentChoice - 1;
            if(currentChoice < 0)
            {
                currentChoice = 3;
            }
        }
        else if(Gdx.input.isKeyJustPressed(Input.Keys.DOWN))
        {
            System.out.println("DOWN");
            currentChoice = currentChoice + 1;
            if(currentChoice > 3)
            {
                currentChoice = 0;
            }
        }
        System.out.println(currentChoice);

**Comment by tomcashman** [comment]
It is possible that [multiple updates occur before interpolate and render](https://github.com/mini2Dx/mini2Dx/wiki/Basic-Concepts) depending on the hardware. However, it seems that the input is not updated if this happens - I will fix this.

Note that your code should assume that multiple updates could occur before interpolate and render.
