### ISSUE TITLE
Generator project - build failed

### ISSUE THREAD

**Issue by nemor2** [mini2Dx/mini2Dx#43]
I can't generate project...    
  > Could not resolve com.battlebardgames.parcl:parcl:1.0.6.
         > Could not get resource 'http://maven.mini2dx.org/content/repositories/releases/com/battlebardgames/parcl/parcl/1.0.6/parcl-1.0.6.pom'.
            > Could not GET 'http://maven.mini2dx.org/content/repositories/releases/com/battlebardgames/parcl/parcl/1.0.6/parcl-1.0.6.pom'. Received status code 503 from server: Service Unavailable
 BUILD FAILED.

Generator was downloaded from main project site.

**Comment by tomcashman** [comment]
Seems our maven server crashed. Fixed now :)
