### ISSUE TITLE
Rectangles are not fully rendered (android)

### ISSUE THREAD

**Issue by mierzrmit** [mini2Dx/mini2Dx#44]
In some cases not all sides of rectangle are rendered on android.
Android:
![screenshot_2015-12-27-17-13-30](https://cloud.githubusercontent.com/assets/4997033/12011009/bca9183a-acbd-11e5-8e92-1402ce410390.png)
PC:
![pc](https://cloud.githubusercontent.com/assets/4997033/12011041/38845090-acbf-11e5-87b4-affc064476c1.png)

I'm using method g.drawShape();

**Comment by tomcashman** [comment]
That's odd. Can I ask if you're using an Android emulator or a specific device?

**Comment by mierzrmit** [comment]
I'm using device with MTK6592 and Mali450.
I've done few test: mtk6592 - like on the screenshot, however my two older devices with qualcomm chip draw rectangles perfectly.

**Comment by tomcashman** [comment]
There's not much I can do if it's device-specific :/ And I can't see anything that would cause this in the code. Unless you have any ideas?

It might be something to do with how the device handles float rounding when rendering to pixels on the screen, maybe try setting the line height to 2? g.setLineHeight(2);

**Comment by mierzrmit** [comment]
When I set line height to 2 it draw at that place line with 1px of height ,all other sides are 2px.
I've made also another test on which I rendered a lot of rectangles and reset it after each 10 sec in loop. I didn't find any another rectangles affected with this bug excluding those two from the picture x). I think you can close this issue.
