### ISSUE TITLE
Add few missing methods/class from slick2d

### ISSUE THREAD

**Issue by Mierzmit** [mini2Dx/mini2Dx#45]
I'm trying to port two games from slick2d.
I'm missing few method /classes:
g.fillShape(shape); 
(it will be faster to type than each time g.fillRect(rect.getX(),rect.getY(),rect.getWidth(),rect.getHeight());.
g.texture(); (shape with texture)
Method contains(x,y) in circle class.
And the my main problem is missing Polygon.class
In slick2d it was very useful to creating any shapes and making collision.(polygon.addPoint(x,y)....)
Is it possibile to add them?
Thanks

**Comment by tomcashman** [comment]
I'll need to investigate how to do g.texture and the Polygon implementation but I'll add the others to the next 1.3.0 alpha in the meantime.

**Comment by Mierzmit** [comment]
It would be good if in next version you could also add methods intersects(shape); in shape classes.
For now I can't check is circle intersects rectangle and vice versa.

**Comment by tomcashman** [comment]
I will tag a new alpha this evening with these new methods.

**Comment by tomcashman** [comment]
1.3.0-beta1 is now available.

**Comment by tomcashman** [comment]
The only missing function is now Graphics.texture(). I've created issue #59 to track this feature.
