### ISSUE TITLE
Draw lines - no transparent/alpha channel

### ISSUE THREAD

**Issue by Mierzmit** [mini2Dx/mini2Dx#48]
I set color with alpha channel using g.setcolor() 
Then I drew lines with g.drawLineSegment() the problem is that they are without any alpha channel

**Comment by tomcashman** [comment]
I currently use LibGDX's [ShapeRenderer](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/glutils/ShapeRenderer.html) to render lines so I'll need to report the issue to their [issue tracker](https://github.com/libgdx/libgdx/issues)

**Comment by tomcashman** [comment]
Can you provide the exact Color you're using?

**Comment by Mierzmit** [comment]
public static Color transBlue = new Color(0.05f,0.1f,1.0f,0.65f);
public static Color transRed = new Color(1f,0.04f,0.0f,0.56f);
And to increase lines size i'm using Gdx.gl.glLineWidth();

**Comment by tomcashman** [comment]
Submitted issue to LibGDX -> https://github.com/libgdx/libgdx/issues/3771
