### ISSUE TITLE
Set image/texture color?

### ISSUE THREAD

**Issue by Mierzmit** [mini2Dx/mini2Dx#49]
Is there a way to set image/texture color?
In slick2d I was able to just set it using g.setColor() and then draw image.
There was also another way using image.setColor(corner, r, g, b); (useful for lighting system).

**Comment by tomcashman** [comment]
Not possible with an instance of [Texture](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/Texture.html) but if you create a [Sprite](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/g2d/Sprite.html) from the Texture you can use sprite.setColor(), however this only supports setting the whole image's color tint, not from a specific corner - you'd need to create an issue with LibGDX if you want this feature added.
