### ISSUE TITLE
Improve test coverage of Rectangle and Circle classes

### ISSUE THREAD

**Issue by tomcashman** [mini2Dx/mini2Dx#53]
Currently test coverage is below 50% for both classes. To prevent regression and resolve any unknown bugs, further tests need to be added to RectangleTest and CircleTest.

**Comment by CauchyAbel** [comment]
I will take a look at this :)

**Comment by CauchyAbel** [comment]
Just a question, how are you checking the coverage under your project? I don't see jacoco available over here, so other alternatives?

**Comment by tomcashman** [comment]
I've just been using the EclEmma plugin for Eclipse so far. Would be good if there was a grade plugin or web service we could set up.

**Comment by CauchyAbel** [comment]
I will try to add the Jacoco plugin which I normally use (at work place) for code coverage under gradle.

**Comment by CauchyAbel** [comment]
Pull request opened for this issue as well as a problem in circle bounding box calculation.
