### ISSUE TITLE
Server down error 503

### ISSUE THREAD

**Issue by srwooow** [mini2Dx/mini2Dx#58]
* What went wrong:
A problem occurred configuring root project 'my-mini2Dx-game'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.battlebardgames.parcl:parcl:1.0.6.
     Required by:
         :my-mini2Dx-game:unspecified
      > Could not resolve com.battlebardgames.parcl:parcl:1.0.6.
         > Could not get resource 'http://maven.mini2dx.org/content/repositories/thirdparty/com/battlebardgames/parcl/parcl/1.0.6/parcl-1.0.6.pom'.
            > Could not GET 'http://maven.mini2dx.org/content/repositories/thirdparty/com/battlebardgames/parcl/parcl/1.0.6/parcl-1.0.6.pom'. Received status code 503 from server: Service Unavailable
      > Could not resolve com.battlebardgames.parcl:parcl:1.0.6.
         > Could not get resource 'http://maven.mini2dx.org/content/repositories/releases/com/battlebardgames/parcl/parcl/1.0.6/parcl-1.0.6.pom'.
            > Could not GET 'http://maven.mini2dx.org/content/repositories/releases/com/battlebardgames/parcl/parcl/1.0.6/parcl-1.0.6.pom'. Received status code 503 from server: Service Unavailable

**Comment by tomcashman** [comment]
Maven repo went down temporarily. I've restarted it now and installed a service monitoring tool in case there are issues in the future it will auto-restart and send me alerts.
