### ISSUE TITLE
Forum is down

### ISSUE THREAD

**Issue by mhvelplund** [mini2Dx/mini2Dx#64]
This is not really a code issue, but this was the only place I saw to contact the project owner. The forum link on the main page (https://mini2dx.org/forum/) is broken.

**Comment by tomcashman** [comment]
Nobody used the old forum :/

I'm currently working on a new website + forum to try grow the community. Hoping to launch it at the same time as 1.3.0 in August :)

**Comment by mhvelplund** [comment]
;)
