### ISSUE TITLE
Project Generator add mini2dx source

### ISSUE THREAD

**Issue by LuisPeregrina** [mini2Dx/mini2Dx#65]
It would be great to download the source of the mini2dx. There are already other sources.

**Comment by tomcashman** [comment]
I'm not sure why this is needed when the source can be download from Github? It seems outside the scope of a "Project Generator"?

**Comment by LuisPeregrina** [comment]
Exactly, the project generator is supposed to avoid or skip the steps to download libraries. I wanted to see what was the internals of the library I´m using but was surprised that the source was missing. What I mean is it should have the option to download the source, not necessarily pre selected.

**Comment by tomcashman** [comment]
Do you mean when using an IDE you want to be able to see the source of the mini2Dx classes? If so, starting with 1.3.0 the source is uploaded with the binaries to Maven Central.

**Comment by tomcashman** [comment]
Source now included on Maven Central for 1.3.0
