### ISSUE TITLE
Maven repo errors

### ISSUE THREAD

**Issue by aequis** [mini2Dx/mini2Dx#69]
I used the Windows mini2dx project generator to create a project for IntelliJ IDEA. But when I try to open the project, IDEA is unable to connect to and update some of the Maven repos. Specifically,

https://mini2dx.org/maven/content/repositories/releases
https://mini2dx.org/maven/content/repositories/thirdparty

It says "Error" and "FileNotFoundException: Resource nexus-maven-repository-index.properties does not exist".  

Any idea what could be wrong or how to fix this?

**Comment by tomcashman** [comment]
Ah I need to update the templates. These can be removed from build.gradle

**Comment by aequis** [comment]
Okay, thanks

**Comment by tomcashman** [comment]
Fixed in latest version project generator available here -> https://github.com/mini2Dx/mini2Dx-project-generator/releases

Fixed by commit d8d9fef90d6e0b41d0cb398f9d05d8a38ae9bf1e
