### ISSUE TITLE
[Regression] Missing Rectangle#setCenter method from 1.3 onwards

### ISSUE THREAD

**Issue by tomcashman** [mini2Dx/mini2Dx#71]
Rectangle#setCenter(float x, float y) disappeared during the refactoring of shapes to use a Polygon class in 1.3. Re-add this to ensure an upgrade path from 1.2.

**Comment by mikev37** [comment]
How do I get this fix into my game?

**Comment by tomcashman** [comment]
I've now deployed 1.6.4 to Maven Central which includes this fix.
