### ISSUE TITLE
Gid of TileObjects to large for int

### ISSUE THREAD

**Issue by Zweistein2** [mini2Dx/mini2Dx#72]
I got a tiled map with the following objects

`
  <object id="30" name="city" gid="73" x="222" y="288" width="56" height="72">
   <properties>
    <property name="Owner" value="Red"/>
   </properties>
  </object>
`

`
  <object id="42" name="jeep" gid="2147483735" x="732" y="219" width="52" height="44">
   <properties>
    <property name="Owner" value="Blue"/>
   </properties>
  </object>
`

Obviously the generated gid value of the second object (2147483735) is too big for a normal int. This leads to the following error: 

`
Error:java.lang.NumberFormatException: For input string: "2147483715"
`

when trying to access the .getGid()-method

**Comment by tomcashman** [comment]
Looks like Tiled uses unsigned ints internally so I'll need to change this field to a long.

Unfortunately I'm in hospital for the next few days (currently using my phone) so will probably be the weekend by the time I fix this.

**Comment by Zweistein2** [comment]
No problem, I just stumbled upon this small bug.

Get well soon!

**Comment by tomcashman** [comment]
After speaking with Bjorn from Tiled, he mentioned that when the int is too large for a signed int it means that the tile is flipped/rotated (which I had forgotten).

Is this the case for the tile that is causing the error?

**Comment by tomcashman** [comment]
Fix now available in 1.6.5

**Comment by Zweistein2** [comment]
Yep, it is flipped horizontally.
