### ISSUE TITLE
Passing data among Basicscreens

### ISSUE THREAD

**Issue by Javasamurai** [mini2Dx/mini2Dx#75]
So I have multiple screens set up.splash,menu,game and game over.
Is there any way to pass data among game and game over to show score.How do we accomplish that.

`    @Override
    public void update(GameContainer gc, ScreenManager<? extends GameScreen> screenManager, float delta) {
        if (should_exit) {
            screenManager.enterGameScreen(GameOver.ID, new NullTransition(), new FadeInTransition());
        }
    }
`
How do I enter another screen with some relevant data?

**Comment by tomcashman** [comment]
Two ways you could to do it are:

1. Create an object shared between both screens and set the reference via constructor or during initialise() where you create your game screens
2. Use a message bus system such as [minibus](https://github.com/mini2Dx/mini2Dx/wiki/Message-Bus) to send messages between different message listeners

**Comment by Javasamurai** [comment]
1st method worked. Keep doing awesome work. I am participating this year Hacktober. Willing to help.

**Comment by tomcashman** [comment]
That would be great. I'll try make some tasks for hacktober :)
