### ISSUE TITLE
Tiled collision objects support

### ISSUE THREAD

**Issue by cherrydev** [mini2Dx/mini2Dx#76]
Tiles has the ability to draw shapes on top of tiles which ends up in an <objectgroup> element, but unfortunately the TiledParser doesn't recognize them. Also unfortunately, TiledParser is not particularly extensible or amenable to being subclassed. Of course I understand it's more complicated than just modifying the parser, since Tile would then need to optionally contain a collision shape.

What I would use it for is not actually partial tile colliders on maps, but rather, I'm using a Tile as a character sprite and it would be great to use a collider shape already defined on it.

**Comment by tomcashman** [comment]
This is now available in 1.7.14. See [TiledObject#getObjectShape](https://mini2dx.org/javadoc/1.7.14/org/mini2Dx/tiled/TiledObject.html#getObjectShape--), [TiledObject#toCircle](https://mini2dx.org/javadoc/1.7.14/org/mini2Dx/tiled/TiledObject.html#toCircle--), [TiledObject#toRectangle](https://mini2dx.org/javadoc/1.7.14/org/mini2Dx/tiled/TiledObject.html#toRectangle--), etc.

**Comment by cherrydev** [comment]
Hey, that's great! Thanks.
