### ISSUE TITLE
Sprites upside down after update to version 1.9.0-beta.8

### ISSUE THREAD

**Issue by klaushauschild1984** [mini2Dx/mini2Dx#80]
After updating from 1.8.0 to 1.9.0-beta.8 all rendered sprites are upside down. No huge problem, because fliiping after animation was load fixes the problem. But it breaks in some kind the API.
Was this intended. I scanned the changelog but could not find a direct hint.

**Comment by tomcashman** [comment]
Which class are you using that is rendering upside-down?

**Comment by klaushauschild1984** [comment]
Sprite.
But I am not sure whats the real difference between Sprite and Textures is actually.

**Comment by tomcashman** [comment]
Can you provide a code snippet? I checked the UAT project and the Sprite class seems correct but perhaps I'm missing a use case.

Sprite just wraps a Texture with additional metadata to allow for tinting/rotating/etc.

**Comment by tomcashman** [comment]
Found the issue. It was due to an old workaround that's no longer needed. I'll publish another beta this evening and let you know when it's available on Maven Central :)

**Comment by klaushauschild1984** [comment]
Great.

**Comment by tomcashman** [comment]
Fixed in 1.9.0-beta.9 on Maven Central :)
