### ISSUE TITLE
Add ARM architecture support (LWJGL3)

### ISSUE THREAD

**Issue by Torbuntu** [mini2Dx/mini2Dx#83]
Mini2DX would be an excellent platform for developing 2D games targeting the Raspberry Pi and similarly powered SBC's. 

Adding support for the ARM (armhf/aarch64) architectures would hugely expand the supported devices for Mini2DX.

I've seen somewhere mention of possibly porting some backends to [BGFX](https://github.com/bkaradzic/bgfx). It says on the overview page that Raspberry Pi is a supported platform. I would need to look further into it to see the exact capabilities and work involved.  

Otherwise, in keeping with the current Libgdx backends, there is this [open PR](https://github.com/libgdx/libgdx/pull/5556) on the libgdx github page for adding arm support for the libgdx backends. This would make things probably easier than doing it through bgfx. Though bgfx also seems to support the SteamLink. It would be fantastic to be able to build games in Mini2DX to target SteamLink natively!

**Comment by tomcashman** [comment]
Correct that we plan to use BGFX in the future, however, this will come via LWJGL3 and there is an on-going task to support ARM there (https://github.com/LWJGL/lwjgl3/issues/206). So we'll need to wait for that to be implemented first.

However, if the LibGDX PR is merged then we could certainly use that.

**Comment by Torbuntu** [comment]
The PR for ARM on LWJGL3 has been merged! 
[PR link](https://github.com/LWJGL/lwjgl3/pull/463)
This means in a short while the libgdx PR can be merged as well (it is being cleaned up now). But that might not matter so much if Mini2Dx is being shifted to lwjgl3 :)

**Comment by Torbuntu** [comment]
If the Libgdx arm support requires lwjgl3, does that mean that it still wouldn't work for mini2Dx? Since it uses lwjgl2?

**Comment by Torbuntu** [comment]
Since this would most likely come VIA LWJGL3, would it be more appropriate to change the title to something like `Add LWJGL 3 backend` ?

**Comment by tomcashman** [comment]
Yup. Updated now.

**Comment by Torbuntu** [comment]
> Yup. Updated now.

You're the best :+1: Thanks!

**Comment by Torbuntu** [comment]
Thanks to the lwjgl3 backend it is significantly easier to set up an arm build now!

There is still a few steps to make it work though.
- Libgdx still has some natives that need to be compiled for arm. There is still an open pr about it, but until then this has to be manual.
- extensions such as controllers need to be compiled manually. However the controllers are only necessary if one uses the gdx advanced controller extension. The lwjgl3 controllers work out of the box. But they lack some features such as rumble support.

**Comment by Torbuntu** [comment]
Libgdx and lwjgl3 now support arm out of the box.
